title: Roͥboͣcͫo
description: an development enthusiast's documentary blog
#theme: just-the-docs
remote_theme: sighingnow/jekyll-gitbook

url: https://iroboco.github.io

aux_links:
  Template Repository: https://github.com/iRoboco
